// <auto-generated />
namespace LapTimes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IsWaiting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsWaiting));
        
        string IMigrationMetadata.Id
        {
            get { return "201311302333562_IsWaiting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
