// <auto-generated />
namespace LapTimes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameDriversRacers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameDriversRacers));
        
        string IMigrationMetadata.Id
        {
            get { return "201312020138539_RenameDriversRacers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
