// <auto-generated />
namespace LapTimes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RacerNameRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RacerNameRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201311261232473_RacerNameRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
