// <auto-generated />
namespace LapTimes.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SplitRacersDrivers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplitRacersDrivers));
        
        string IMigrationMetadata.Id
        {
            get { return "201311270013347_SplitRacersDrivers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
